# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: [3.7, 3.8, 3.6]
        exclude:
          - os: windows-latest
            python-version: 3.6

#    steps:
#    - uses: actions/checkout@v2
#    - name: Set up Python ${{ matrix.python-version }}
#      uses: actions/setup-python@v2
#      with:
#        python-version: ${{ matrix.python-version }}
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install dask==2021.3.0 dask-glm==0.2.0 dask-ml==1.8.0 dask-xgboost==0.1.11  scikit-learn==0.23 featuretools==0.27.1
#        pip install git+https://github.com/DataCanvasIO/HyperBoard.git#subdirectory=hboard-widget
#        pip install git+https://github.com/DataCanvasIO/HyperBoard.git#subdirectory=hboard
#        pip install -q -r requirements.txt
#        pip install -q pytest-cov==2.4.0
#        pip list
#    - name: Test with pytest
#      run: |
#        pytest --cov=hypergbm --durations=30
